import fs from 'fs';

const cwd = process.cwd();
export async function removeAutogeneratedConfigFile(): Promise<void> {
  try {
    await fs.promises.unlink(`${cwd}/.versionguardrc.json`);
  } catch (e) {
    // file didn't exist
  }
}
